"use client";

import { useState } from "react";
import useSWR from "swr";
import { Button } from "@/components/ui/button";
import { FormAlert } from "@/components/ui/field";
import { ApiError } from "@/lib/api";
import { cn } from "@/lib/utils";
import { catalogService, type Media } from "@/services/catalog";

/**
 * The media library, as a dialog.
 *
 * Built once and opened from five admin screens - categories, brands and the
 * product image tab among them - because the alternative is the same grid
 * copy-pasted five times and drifting.
 *
 * Conversions are generated by a queued job, so a freshly uploaded image comes
 * back `processing` with its thumbnail falling back to the original. The list
 * revalidates so it settles on its own rather than looking broken.
 */
export function MediaPicker({
  open,
  multiple = false,
  onClose,
  onSelect,
}: {
  open: boolean;
  multiple?: boolean;
  onClose: () => void;
  onSelect: (media: Media[]) => void;
}) {
  const [picked, setPicked] = useState<Media[]>([]);
  const [uploading, setUploading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const { data, mutate, isLoading } = useSWR(
    open ? "/admin/media" : null,
    async () => (await catalogService.admin.media({ per_page: 60 })).items,
    {
      shouldRetryOnError: false,
      // Poll only while something is still being processed.
      refreshInterval: (items) =>
        items?.some((m) => m.status === "processing") ? 2000 : 0,
    },
  );

  if (!open) return null;

  async function upload(files: FileList | null) {
    if (!files?.length) return;

    setError(null);
    setUploading(true);

    try {
      for (const file of Array.from(files)) {
        await catalogService.admin.uploadMedia(file);
      }

      await mutate();
    } catch (e) {
      setError(e instanceof ApiError ? e.displayMessage : "Upload failed");
    } finally {
      setUploading(false);
    }
  }

  function toggle(media: Media) {
    setPicked((current) => {
      const already = current.some((m) => m.id === media.id);

      if (already) return current.filter((m) => m.id !== media.id);

      return multiple ? [...current, media] : [media];
    });
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-6"
      role="dialog"
      aria-modal="true"
      aria-label="Media library"
    >
      <div className="bg-card flex max-h-[85vh] w-full max-w-4xl flex-col rounded-lg border shadow-lg">
        <div className="flex items-center justify-between border-b px-5 py-3">
          <h2 className="font-semibold">Media library</h2>
          <button onClick={onClose} className="text-sm underline">
            Close
          </button>
        </div>

        <div className="space-y-3 border-b px-5 py-3">
          {error && <FormAlert message={error} />}

          <label className="inline-flex cursor-pointer items-center gap-2 text-sm">
            <input
              type="file"
              multiple
              accept="image/jpeg,image/png,image/webp,image/avif"
              className="hidden"
              onChange={(event) => upload(event.target.files)}
            />
            <span className="bg-secondary text-secondary-foreground rounded-md px-3 py-2">
              {uploading ? "Uploading…" : "Upload images"}
            </span>
          </label>

          <p className="text-muted-foreground text-xs">
            JPEG, PNG, WebP or AVIF. Thumbnails are generated in the background.
          </p>
        </div>

        <div className="min-h-0 flex-1 overflow-y-auto p-5">
          {isLoading && <p className="text-muted-foreground text-sm">Loading…</p>}

          {data?.length === 0 && (
            <p className="text-muted-foreground text-sm">Nothing uploaded yet.</p>
          )}

          <ul className="grid grid-cols-3 gap-3 sm:grid-cols-5">
            {data?.map((media) => {
              const selected = picked.some((m) => m.id === media.id);

              return (
                <li key={media.id}>
                  <button
                    onClick={() => toggle(media)}
                    className={cn(
                      "block w-full overflow-hidden rounded-md border-2",
                      selected ? "border-primary" : "border-transparent",
                    )}
                  >
                    <span className="bg-muted block aspect-square">
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img
                        src={media.thumb_url}
                        alt={media.alt ?? media.filename}
                        className="h-full w-full object-cover"
                      />
                    </span>
                    <span className="text-muted-foreground block truncate p-1 text-xs">
                      {media.status === "processing" ? "processing…" : media.filename}
                    </span>
                  </button>
                </li>
              );
            })}
          </ul>
        </div>

        <div className="flex items-center justify-end gap-2 border-t px-5 py-3">
          <Button variant="ghost" onClick={onClose}>
            Cancel
          </Button>
          <Button
            disabled={picked.length === 0}
            onClick={() => {
              onSelect(picked);
              setPicked([]);
              onClose();
            }}
          >
            {multiple ? `Add ${picked.length || ""}`.trim() : "Choose"}
          </Button>
        </div>
      </div>
    </div>
  );
}
